name: 'Setup Steam Game (Windows)'
description: 'Installs a Windows Steam game'
branding:
  icon: box
  color: gray-dark

inputs:
  username:
    description: 'Log into Steam using this user'
    required: false
    default: 'anonymous'
  password:
    description: 'The password for the user to log into Steam with'
    required: false
    default: ''
  gameid:
    description: 'The ID of the game you want to set up on Steam'
    required: true
  folder:
    description: 'The name of the folder to download the game into. If the folder exists, the game will be verified.'
    required: true
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/setup-steamcmd.ps1
      shell: pwsh
    - run: ${{ github.action_path }}/setup-steam-game.ps1 "${{ inputs.gameid }}" "${{ inputs.folder }}" "windows" "${{ inputs.username }}" "${{ inputs.password }}"
      shell: pwsh
